from __future__ import annotations

import argparse
from hashlib import sha256
from pathlib import Path

from tools.hant_dictionary_definitions import build_official_dictionary_definitions
from tools.inspect_english_bytes import parse


def _file_sha256(path: Path) -> str:
    digest = sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def render_module(elf: Path, english_bytes: Path) -> str:
    raw = elf.read_bytes()
    english_rows = tuple(parse(english_bytes))
    definitions = build_official_dictionary_definitions(raw, english_rows)

    lines = [
        "from __future__ import annotations",
        "",
        "# Generated by tools.generate_hant_dictionary_definitions from the pristine",
        "# PS2 executable and the owned CUSA27034 English.bytes localization corpus.",
        "# Do not hand-edit; regenerate so source fingerprints and official provenance stay fail-closed.",
        f'HANT_DICTIONARY_SOURCE_ELF_SHA256 = "{_file_sha256(elf)}"',
        f'HANT_DICTIONARY_ENGLISH_BYTES_SHA256 = "{_file_sha256(english_bytes)}"',
        "",
        "HANT_DICTIONARY_DEFINITION_DATA: tuple[",
        "    tuple[str, int, int, int, str, tuple[str, ...], str], ...",
        "] = (",
    ]
    for definition in definitions:
        lines.extend(
            [
                "    (",
                f"        {definition.key!r},",
                f"        0x{definition.descriptor_offset:06X},",
                f"        0x{definition.source_table_offset:06X},",
                f"        {definition.source_row_count},",
                f"        {definition.source_sha256!r},",
                "        (",
            ]
        )
        for row in definition.english_rows:
            lines.append(f"            {row!r},")
        lines.extend(
            [
                "        ),",
                f"        {definition.provenance!r},",
                "    ),",
            ]
        )
    lines.extend([")", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate all official H.A.N.T Dictionary definition tables")
    parser.add_argument("--elf", type=Path, required=True)
    parser.add_argument("--english-bytes", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    rendered = render_module(args.elf, args.english_bytes)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8")
    print(f"output={args.output}")
    print("definitions=208")
    print("official_exact_rows=2073")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
